config-version: "2.0.7" #Please don't change this manually

#Tool cooldown length in seconds (defaults to half a second)
#Used for brushes, selection axes and more
#Lowering this might cause some unintended behavior on mobile devices
brush-cooldown: 0.5

#Whether to allow user with "easyedit.history.other" permission to undo/redo other people's actions
allow-history-other: true

#Remaps usages of 3 or more slashes to 2 slashes, allowing usage of minecraft autocomplete
#Disable this if you have commands requiring 3 slashes
remap-commands: true

#Whether to allow setting blocks which are not registered
#Enabling this allows setting blocks which are not registered, but might cause issues like game crashes or world corruption
allow-unregistered-blocks: false

#Max blocks to use fast set on
#Fast set allows to set blocks without any flickering, but triples execution time
#This is also somewhat harsh on client and network performance, so better not set this to high; default:256000
fast-set-max: 256000

#Distance to check while filling; default:200
fill-distance: 200

#Max blocks checked when pathfinding, default: 1000000 (1M)
pathfinding-max: 1000000

#Blocks which get ignored when calculating terrain height (e.g. when smoothing) or inserting selection
terrain-ignored-blocks: [ "air", "wood", "wood2", "leaves", "leaves2", "dandelion", "poppy", "tall_grass", "water", "8", "lava", "10", "snow_layer", "carpet" ]

#Whether to send spammy debug messages into the console
#requires server to be on debug mode
send-debug: false


#Better don't change this, the following is mainly for transparency
#Conversion data source, requires specific Format
#for more information see https://github.com/platz1de/EasyEdit-Data/tree/format-v2.0
#If you want to use your own data, the simplest way is to fork the data repository and modify some values
bedrock-convert-data: "https://raw.githubusercontent.com/platz1de/EasyEdit-Data/format-v2.0/bedrock-conversion-map.json"
bedrock-palette-data: "https://raw.githubusercontent.com/platz1de/EasyEdit-Data/format-v2.0/bedrock_palette.json"
java-palette-data: "https://raw.githubusercontent.com/platz1de/EasyEdit-Data/format-v2.0/java_palette.json"
rotation-data: "https://raw.githubusercontent.com/platz1de/EasyEdit-Data/format-v2.0/rotation-data.json"
flip-data: "https://raw.githubusercontent.com/platz1de/EasyEdit-Data/format-v2.0/flip-data.json"
tile-data-states: "https://raw.githubusercontent.com/platz1de/EasyEdit-Data/format-v2.0/tile-data-states.json"
java-tile-states: "https://raw.githubusercontent.com/platz1de/EasyEdit-Data/format-v2.0/java-tile-states.json"